[tool.poetry]
name = "kirvanowebhook"
version = "0.1.0"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
pydantic-settings = "^2.6.1"
beanie = "^1.27.0"
uvicorn = "^0.32.0"
fastapi = "^0.115.4"
aiosmtplib = "^3.0.2"
